version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_AUTH_URL=http://localhost:3002 # Adaptez selon votre config
      - NEXT_PUBLIC_API_URL=http://localhost:3001   # Adaptez selon votre config
    # Cette option permet au container de redémarrer automatiquement
    restart: unless-stopped 